### ISSUE TITLE
Suggestion: reduction of output data size.

### ISSUE THREAD

**Issue by heartsh** [fukunagatsu/RIblast#4]
A whole of output is so huge when comprehensive analysis is done, for example,  for about 1800 ncRNAs vs themselves plus about 5000 mRNAs the entire output size reaches to ~ 255GB. 
The base pair series of the detected interaction seems to be reduced to the pair of the start & end positions of a query & a  reference.

**Comment by fukunagatsu** [comment]
Thank you for your suggestions. 

I cannot replace the base pair series of the detected interaction with the start and end positions of interactions because two piecies of information are eqaul. If the detected interaction includes internal loop or bulge loop, the base pairs of the detected interaction cannot be inferred from of the start and end positions of interactions. 

I will inplement your suggestion as an alternative output format.

**Comment by fukunagatsu** [comment]
I implemented your suggestion.
