### ISSUE TITLE
Problem with the db command

### ISSUE THREAD

**Issue by pratik-narain** [fukunagatsu/RIblast#6]
I am trying to process a fasta file containing 373 RNA sequences and the db command ends with the message "Killed". I get 3 output files viz. "db.cc", "db.bas" and "db.nam". Now when I run the "ris" command, I get the error message saying that "db.seq" cannot be found. Any help would be appreciated.

**Comment by heartsh** [comment]
HI, I'm not the developer of this program, so my assumption may be wrong.
The message "killed" usually means your computer has run out of the memory due to computation.
Since your DB lacks the sequence file, the above exhaustion seems to have occurred during the suffix array construction.
To confirm what the factor really is, you could use the below debugging:
$ RIblast db -i inpt_fl.fa -o inpt_fl_db & # "&" means that your command will run in background. (The background execution enables you to run the other commands continually.)
$ top # Show you how much memory RIblast consumes.
As a remedy against it, to use another computer with richer memory will be effective.

**Comment by pratik-narain** [comment]
Thanks for the reply. I am running on an Intel core i5 6th generation with 4 GB RAM and Nvidia GT210 GPU. The OS is arch linux with latest updates. Can you please suggest the configuration I should use?

**Comment by heartsh** [comment]
The acceptable configuration depends on your data set.
If acceptable, you could also split the data set for DB into some chunks then run RIblast on each chunk.
To determine a number of the split, you could run the above debugging.
But, first of all, you should determine if the disorder is really caused by lack of memory. (To narrow down a number of possible factors of a bug is a basis of debugging.)
If you couldn't observe the exhaustion with the command "top" (the term "RES" corresponds to amount of used memory), you would need to consider the other factors (for example, any bug in the DB construction depending on your architecture/data set).

**Comment by pratik-narain** [comment]
Okk. Thanks. I'll try this and get back to you.

**Comment by fukunagatsu** [comment]
Hi heartsh,
Thanks for your approprite reply intead of me.
